site_name: JavaScript Docs

site_description: Documentación y tutoriales sobre JavaScrip, sus derivados y sus herramientas asociadas
site_url: https://alejrot.github.io/javascript-docs/


# Repositorio
repo_url: https://github.com/alejrot/javascript-docs
repo_name: javascript-docs
edit_uri: edit/master/docs/

copyright: Copyright &copy; 2024 Marcelo Marot Rosas



theme:
  name: material
  language: es
  font: false   # previene carga de Google Fonts

  icon: 
    # logo: fontawesome/solid/user-nurse
    # logo: fontawesome/brands/node-js  # :fontawesome-brands-node-js:
    # logo: fontawesome/brands/node # :fontawesome-brands-node:
    logo: simple/javascript # :simple-javascript:
    # iconos de avance y retroceso 
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
    # Icono de repositorio    
    repo: fontawesome/brands/github
    #  iconos de etiquetas
    tag:
      html: fontawesome/brands/html5
      js: fontawesome/brands/js
      css:  fontawesome/brands/css3
      yaml: simple/yaml
      python: fontawesome/brands/python
      docker: fontawesome/brands/docker
      podman: simple/podman
      markdown: fontawesome/brands/markdown
      mkdocs: simple/materialformkdocs
      ts: simple/typescript
      csv: fontawesome/solid/file-csv
      bash: simple/gnubash
      express: simple/express
      reactjs: simple/react
      nodejs: fontawesome/brands/node-js
      npm:  material/npm
      pnpm: simple/pnpm
      vitejs: simple/vite
      tsnode: simple/tsnode

      # icono comodín
      # default: material/cursor-default-click


  # carpeta local con extras (opcional)
  # custom_dir: overrides

  palette:
  # Palette toggle for light mode
  # - media: "(prefers-color-scheme)"
  #   toggle:
  #     icon: material/lightbulb-auto
  #     name: Modo automático
      
  # Palette toggle for light mode
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: yellow
    accent: amber
    toggle:
      icon: material/lightbulb 
      name: Modo claro

  # Palette toggle for dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: yellow
    accent: amber
    # accent: light green
    toggle:
      icon: material/lightbulb-outline
      name: modo oscuro


  features:

    - content.tabs.link         # pestañas sincronizadas
    - content.code.copy         # botón de copia 
    - content.code.annotate     # botones de anotaciones emergentes
    # carga instantánea (requiere site_url)
    - navigation.instant
    - navigation.instant.preview
    - navigation.instant.progress   # progreso de carga (conexiones lentas)
    - navigation.tracking
    # pestañas de contenido
    - navigation.tabs
    # - navigation.tabs.sticky
    # - navigation.sections
    - navigation.expand
    - navigation.top  # boton emergente para volver al inicio  - aparece al intentar subir con el scroll
    # Pie de pagina
    - navigation.footer

    # sugerencias de busqueda y remarcar resultados
    - search.suggest
    - search.highlight
    - search.share    # boton compartir
    # header
    - header.autohide # ocultamiento automatico

    - content.code.copy # copiad bloques de codigo
    - content.code.annotate # anotaciones desplegables en código
    
    - content.tabs.link # pestañas interna solidarias
    # header y anuncios
    - header.autohide
    - announce.dismiss

    # acciones sobre repositorio
    # - content.action.edit
    - content.action.view

    # tooltips
    - content.tooltips


extra_css:
  # - stylesheets/extra.css
  - stylesheets/iconos.css

plugins:
 # Imagenes
  - glightbox

  # privacidad - hace copia local de contenidos remotos
  # - privacy

  # busqueda
  - search

  # etiquetas

  - tags:
      tags_file: tags.md

  # fechas de repositorio
  - git-revision-date-localized:
      enabled: true
      enable_creation_date: true
      type: date        # fecha
      # type: datetime    # fecha y hora
      # type: iso_date    # fecha ISO (sólo numeros)
      # type: iso_datetime  # fecha ISO (sólo numeros)
      # type: timeago       # tiempo desde publicación
      fallback_to_build_date: true


extra:

  # Etiquetas de contenidos
  tags:
    HTML5: html
    JavaScript: js
    CSS: css
    YAML: yaml
    Python: python
    Docker: docker 
    Podman: podman 
    MarkDown: markdown
    MkDocs: mkdocs
    TypeScript: ts
    CSV: csv
    Bash: bash 
    Express: express
    ReactJS: reactjs
    NodeJS: nodejs
    NPM: npm
    PNPM: pnpm
    ViteJS: vitejs
    TSNode: tsnode

markdown_extensions:
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - tables
  - pymdownx.tabbed:
      alternate_style: true

nav:
  - Indice: index.md
  - JavaScript:
    - Comenzando: js/comenzando.md
    - Document Object Model (DOM): js/DOM.md

  - NodeJS: 
    - NodeJS - Introducción: node/intro-node.md
    - Módulos: node/modulo.md
    - JSON: node/json.md
    - Asincronía: node/asincronia.md
    - NPM: node/npm.md
    - Eventos y Promesas: node/eventos_promesas.md
    - Modelo Cliente - Servidor: node/cliente-servidor.md


  - TypeScript: 
    - TypeScript - Introducción: ts/intro-ts.md
    - TS-Node: ts/tsnode.md
    - Ejecutar: ts/ejecutar.md
    - Tipado: ts/tipado.md  
    - Datos primitivos: ts/primitivos.md  
    - Datos compuestos: ts/compuestos.md  
    - Funciones: ts/funciones.md
    - Clases: ts/clases.md
    - Interfases: ts/interfases.md
    - Tipos: ts/tipos.md

  - ReactJS: React.md 

  - Express: Express.md

  - Indice de tags: tags.md